/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pharmaciticalstoremanagement.UI;

import BusinessLogic.medicine;
import BusinessLogic.users;
import java.awt.GridLayout;
import java.awt.Image;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MAJEED
 */
public class ManageUsers extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMedicine
     */
    ResultSet rs = users.getAllUser();
    private int userID = 0;
    DefaultTableModel dtm;
    Blob profileImage;

    public ManageUsers() {
        initComponents();
        displayUsers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdateMedicinejPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usersJTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userNamejLabel = new javax.swing.JLabel();
        firstNamejLabel = new javax.swing.JLabel();
        lastNamejLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        statusljLabel = new javax.swing.JLabel();
        deletejButton = new javax.swing.JButton();
        profilePicsjLabel = new javax.swing.JLabel();
        updateUserInfojButton = new javax.swing.JButton();
        refreshjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        UpdateMedicinejPanel.setBackground(new java.awt.Color(255, 255, 255));
        UpdateMedicinejPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(255, 255, 255)));

        usersJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "User Name", "First Name", "Last Name", "Email", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        usersJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersJTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(usersJTable);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("User name:");

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("First name:");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Last name:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Emai:");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel5.setText("Status:");

        userNamejLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        userNamejLabel.setForeground(new java.awt.Color(51, 0, 204));

        firstNamejLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        firstNamejLabel.setForeground(new java.awt.Color(51, 0, 204));

        lastNamejLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        lastNamejLabel.setForeground(new java.awt.Color(51, 0, 204));

        emailjLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        emailjLabel.setForeground(new java.awt.Color(255, 153, 0));

        statusljLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        statusljLabel.setForeground(new java.awt.Color(51, 204, 0));

        deletejButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deletejButton.setForeground(new java.awt.Color(255, 0, 0));
        deletejButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.jpg"))); // NOI18N
        deletejButton.setText("Delete");
        deletejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButtonActionPerformed(evt);
            }
        });

        profilePicsjLabel.setBackground(new java.awt.Color(255, 255, 255));
        profilePicsjLabel.setOpaque(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(firstNamejLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(userNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lastNamejLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(emailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(statusljLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(profilePicsjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletejButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(userNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(firstNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lastNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(emailjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statusljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(profilePicsjLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(deletejButton)
                .addGap(54, 54, 54))
        );

        updateUserInfojButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        updateUserInfojButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/editUser.jpg"))); // NOI18N
        updateUserInfojButton.setText("Update user information");
        updateUserInfojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserInfojButtonActionPerformed(evt);
            }
        });

        refreshjButton.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        refreshjButton.setForeground(new java.awt.Color(0, 102, 0));
        refreshjButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/reset.png"))); // NOI18N
        refreshjButton.setText("Refreshed");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UpdateMedicinejPanelLayout = new javax.swing.GroupLayout(UpdateMedicinejPanel);
        UpdateMedicinejPanel.setLayout(UpdateMedicinejPanelLayout);
        UpdateMedicinejPanelLayout.setHorizontalGroup(
            UpdateMedicinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdateMedicinejPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(UpdateMedicinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdateMedicinejPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdateMedicinejPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(refreshjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateUserInfojButton)
                        .addGap(138, 138, 138))))
        );
        UpdateMedicinejPanelLayout.setVerticalGroup(
            UpdateMedicinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(UpdateMedicinejPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UpdateMedicinejPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateUserInfojButton)
                    .addComponent(refreshjButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateMedicinejPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UpdateMedicinejPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void displayUsers() {
        ResultSet rs = users.getAllUser();
        dtm = (DefaultTableModel) usersJTable.getModel();
        dtm.setRowCount(0);
        try {
            while (rs.next()) {
                String ID = rs.getString("idUser");
                String Username = rs.getString("Username");
                String Firstname = rs.getString("Firstname");
                String Lastname = rs.getString("Lastname");
                String Email = rs.getString("Email");
                String Status = rs.getString("Status");

                dtm.addRow(new Object[]{ID, Username, Firstname, Lastname, Email, Status});
                usersJTable.getColumnModel().getColumn(0).setPreferredWidth(8);

            }
        } catch (SQLException ex) {
            Logger.getLogger(medicine.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void usersJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersJTableMouseClicked
        // TODO add your handling code here:
        int rowNum = usersJTable.getSelectedRow();
        Object ID = usersJTable.getValueAt(rowNum, 0);
        Object userName = usersJTable.getValueAt(rowNum, 1);
        Object firstName = usersJTable.getValueAt(rowNum, 2);
        Object lastName = usersJTable.getValueAt(rowNum, 3);
        Object email = usersJTable.getValueAt(rowNum, 4);
        Object status = usersJTable.getValueAt(rowNum, 5);

        userID = Integer.valueOf((String) ID);
        userNamejLabel.setText((String) userName);
        firstNamejLabel.setText((String) firstName);
        lastNamejLabel.setText((String) lastName);
        emailjLabel.setText((String) email);
        statusljLabel.setText((String) status);
        rs = users.getProfileImage((int) userID);

        try {
            while (rs.next()) {
                profileImage = rs.getBlob("ProfilePictures");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        }

        byte[] content = null;
        try {
            content = profileImage.getBytes(1, (int) profileImage.length());
        } catch (SQLException ex) {
            Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
        }

        ImageIcon ik1 = new ImageIcon(content);
        Image img = ik1.getImage();
        Image newimg = img.getScaledInstance(profilePicsjLabel.getWidth(), profilePicsjLabel.getHeight(), java.awt.Image.SCALE_SMOOTH);
        ImageIcon ik = new ImageIcon(newimg);
        //System.out.println(newimg);
        profilePicsjLabel.setIcon(ik);

        //profilePicsjLabel.setIcon(new ImageIcon(profileImage));

    }//GEN-LAST:event_usersJTableMouseClicked

    private void updateUserInfojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserInfojButtonActionPerformed
        // TODO add your handling code here:
        if (userID == 0) {
            JOptionPane.showMessageDialog(null, "You have not select any user", "select user to update",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            ResultSet userInfo = users.getAUser(userID);
            JPanel updateUserInfoJpanel = new JPanel();
            updateUserInfoJpanel.setLayout(new BoxLayout(updateUserInfoJpanel, BoxLayout.X_AXIS));

            JPanel labelsJPanel = new JPanel();
            labelsJPanel.setLayout(new GridLayout(0, 1));

            JLabel userNameLabel = new JLabel("User name:", JLabel.RIGHT);
            JLabel firstNameLabel = new JLabel("First name:", JLabel.RIGHT);
            JLabel lastNameLabel = new JLabel("Last name:", JLabel.RIGHT);
            JLabel emailLabel = new JLabel("Email:", JLabel.RIGHT);
            JLabel passwordLabel = new JLabel("Password:", JLabel.RIGHT);
            JLabel statusLabel = new JLabel("User status:", JLabel.RIGHT);

            labelsJPanel.add(userNameLabel);
            labelsJPanel.add(firstNameLabel);
            labelsJPanel.add(lastNameLabel);
            labelsJPanel.add(emailLabel);
            labelsJPanel.add(passwordLabel);
            labelsJPanel.add(statusLabel);

            JPanel textFieldJPanel = new JPanel();
            textFieldJPanel.setLayout(new GridLayout(0, 1));

            JTextField UserName = new JTextField();
            JTextField FirstName = new JTextField();
            JTextField LastName = new JTextField();
            JTextField Email = new JTextField();
            JTextField Password = new JTextField();
            JTextField Status = new JTextField();

            try {
                while (userInfo.next()) {
                    UserName.setText(userInfo.getString("Username"));
                    FirstName.setText(userInfo.getString("Firstname"));
                    LastName.setText(userInfo.getString("Lastname"));
                    Email.setText(userInfo.getString("Email"));
                    Password.setText(userInfo.getString("Password"));
                    Status.setText(userInfo.getString("Status"));

                }
            } catch (SQLException ex) {
                Logger.getLogger(ManageUsers.class.getName()).log(Level.SEVERE, null, ex);
            }

            textFieldJPanel.add(UserName);
            textFieldJPanel.add(FirstName);
            textFieldJPanel.add(LastName);
            textFieldJPanel.add(Email);
            textFieldJPanel.add(Password);
            textFieldJPanel.add(Status);

            updateUserInfoJpanel.add(labelsJPanel);
            updateUserInfoJpanel.add(textFieldJPanel);

            int getUserInfo = JOptionPane.showConfirmDialog(null, updateUserInfoJpanel, "Update user inforation",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (getUserInfo == JOptionPane.OK_OPTION) {
                ArrayList userInfoToUpdate = new ArrayList<String>();
                userInfoToUpdate.add(userID);
                userInfoToUpdate.add(UserName.getText());
                userInfoToUpdate.add(FirstName.getText());
                userInfoToUpdate.add(LastName.getText());
                userInfoToUpdate.add(Email.getText());
                userInfoToUpdate.add(Password.getText());
                userInfoToUpdate.add(Status.getText());

                users.updateUserData(userInfoToUpdate);
            }
        }
    }//GEN-LAST:event_updateUserInfojButtonActionPerformed

    private void deletejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButtonActionPerformed
        // TODO add your handling code here:
        int rowToRemove = usersJTable.getSelectedRow();
        String user_ID = (String) usersJTable.getValueAt(rowToRemove, 0);
        if (rowToRemove == -1) {
            JOptionPane.showMessageDialog(null, "Select User to delete", "Select user to delete",
                    JOptionPane.INFORMATION_MESSAGE);
        } else {
            users.deleteUser(user_ID);
            ((DefaultTableModel) usersJTable.getModel()).removeRow(rowToRemove);
            ((DefaultTableModel) usersJTable.getModel()).fireTableDataChanged();
        }
    }//GEN-LAST:event_deletejButtonActionPerformed

    private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
        // TODO add your handling code here:
        displayUsers();
    }//GEN-LAST:event_refreshjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UpdateMedicinejPanel;
    private javax.swing.JButton deletejButton;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JLabel firstNamejLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNamejLabel;
    private javax.swing.JLabel profilePicsjLabel;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JLabel statusljLabel;
    private javax.swing.JButton updateUserInfojButton;
    private javax.swing.JLabel userNamejLabel;
    private javax.swing.JTable usersJTable;
    // End of variables declaration//GEN-END:variables
}
